###################################################
# Recipes auto-generated by gendeps.py script.    #
# These recipes should not be edited by hand; any #
# changes will be overwritten.                    #
###################################################

$(ODIR)/agent.o: $(SDIR)/agent.cpp $(SDIR)/agent.hpp $(SDIR)/msa.hpp $(SDIR)/configuration.hpp $(SDIR)/agent_hooks.hpp $(SDIR)/log.hpp $(SDIR)/output.hpp $(SDIR)/var.hpp
	$(CXX) -c -o $@ $(SDIR)/agent.cpp $(CXXFLAGS)

$(ODIR)/util.o: $(SDIR)/util.cpp $(SDIR)/util.hpp
	$(CXX) -c -o $@ $(SDIR)/util.cpp $(CXXFLAGS)

$(ODIR)/msa.o: $(SDIR)/msa.cpp $(SDIR)/msa.hpp $(SDIR)/agent.hpp $(SDIR)/configuration.hpp $(SDIR)/agent_hooks.hpp $(SDIR)/input.hpp $(SDIR)/cmd.hpp $(SDIR)/event/handler.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp $(SDIR)/event/dispatch.hpp $(SDIR)/log.hpp $(SDIR)/output.hpp $(SDIR)/string.hpp $(SDIR)/plugin.hpp
	$(CXX) -c -o $@ $(SDIR)/msa.cpp $(CXXFLAGS)

$(ODIR)/event/event.o: $(SDIR)/event/event.cpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp
	$(CXX) -c -o $@ $(SDIR)/event/event.cpp $(CXXFLAGS)

$(ODIR)/event/handler.o: $(SDIR)/event/handler.cpp $(SDIR)/event/handler.hpp $(SDIR)/msa.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp
	$(CXX) -c -o $@ $(SDIR)/event/handler.cpp $(CXXFLAGS)

$(ODIR)/event/dispatch.o: $(SDIR)/event/dispatch.cpp $(SDIR)/event/dispatch.hpp $(SDIR)/msa.hpp $(SDIR)/event/handler.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp $(SDIR)/configuration.hpp $(SDIR)/util.hpp $(SDIR)/log.hpp
	$(CXX) -c -o $@ $(SDIR)/event/dispatch.cpp $(CXXFLAGS)

$(ODIR)/input.o: $(SDIR)/input.cpp $(SDIR)/input.hpp $(SDIR)/msa.hpp $(SDIR)/configuration.hpp $(SDIR)/event/dispatch.hpp $(SDIR)/event/handler.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp $(SDIR)/util.hpp $(SDIR)/log.hpp
	$(CXX) -c -o $@ $(SDIR)/input.cpp $(CXXFLAGS)

$(ODIR)/string.o: $(SDIR)/string.cpp $(SDIR)/string.hpp
	$(CXX) -c -o $@ $(SDIR)/string.cpp $(CXXFLAGS)

$(ODIR)/configuration.o: $(SDIR)/configuration.cpp $(SDIR)/configuration.hpp $(SDIR)/string.hpp
	$(CXX) -c -o $@ $(SDIR)/configuration.cpp $(CXXFLAGS)

$(ODIR)/cmd.o: $(SDIR)/cmd.cpp $(SDIR)/cmd.hpp $(SDIR)/msa.hpp $(SDIR)/configuration.hpp $(SDIR)/event/handler.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp $(SDIR)/event/dispatch.hpp $(SDIR)/string.hpp $(SDIR)/agent.hpp $(SDIR)/agent_hooks.hpp $(SDIR)/log.hpp
	$(CXX) -c -o $@ $(SDIR)/cmd.cpp $(CXXFLAGS)

$(ODIR)/log.o: $(SDIR)/log.cpp $(SDIR)/log.hpp $(SDIR)/msa.hpp $(SDIR)/configuration.hpp $(SDIR)/string.hpp $(SDIR)/util.hpp
	$(CXX) -c -o $@ $(SDIR)/log.cpp $(CXXFLAGS)

$(ODIR)/output.o: $(SDIR)/output.cpp $(SDIR)/output.hpp $(SDIR)/msa.hpp $(SDIR)/configuration.hpp $(SDIR)/log.hpp $(SDIR)/string.hpp
	$(CXX) -c -o $@ $(SDIR)/output.cpp $(CXXFLAGS)

$(ODIR)/var.o: $(SDIR)/var.cpp $(SDIR)/var.hpp
	$(CXX) -c -o $@ $(SDIR)/var.cpp $(CXXFLAGS)

$(ODIR)/plugin.o: $(SDIR)/plugin.cpp $(SDIR)/plugin.hpp $(SDIR)/msa.hpp $(SDIR)/cmd.hpp $(SDIR)/configuration.hpp $(SDIR)/event/handler.hpp $(SDIR)/event/event.hpp $(SDIR)/event/topics.hpp $(SDIR)/log.hpp $(SDIR)/agent.hpp $(SDIR)/agent_hooks.hpp $(SDIR)/string.hpp
	$(CXX) -c -o $@ $(SDIR)/plugin.cpp $(CXXFLAGS)

