###################################################
# Recipes auto-generated by gendeps.py script.    #
# These recipes should not be edited by hand; any #
# changes will be overwritten.                    #
###################################################

$(ODIR)/platform/thread.o: $(OS_SDIR)/platform/thread/thread.cpp
	$(CXX) -c -o $@ $(OS_SDIR)/platform/thread/thread.cpp $(CXXFLAGS)

$(ODIR)/platform/file.o: $(OS_SDIR)/platform/file/file.cpp
	$(CXX) -c -o $@ $(OS_SDIR)/platform/file/file.cpp $(CXXFLAGS)

$(ODIR)/platform/lib.o: $(OS_SDIR)/platform/lib/lib.cpp $(OS_SDIR)/platform/file/file.hpp
	$(CXX) -c -o $@ $(OS_SDIR)/platform/lib/lib.cpp $(CXXFLAGS)

